### ISSUE TITLE
Bug Report: Insane FPS studdering while playing the game

### ISSUE THREAD

**Issue by ThePlank** [Verwex/Funkin-Mic-d-Up-SC#65]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows x86_64

## What version of the game are you using?
Artifact from [this build](https://github.com/Verwex/Funkin-Mic-d-Up-SC/runs/2740295489)

## Have you identified any steps to reproduce the bug?

1. Launch the game
2. Play a week

## Please describe your issue.

While playing the game, FPS studders frequently.

## PC specs

- CPU: Intel core I5 8th gen
- GPU: GForce GTX 1050
- RAM: 8GB (7.86 Abalible)
- OS: Windows 10 Version 20H2

**Comment by Purble11** [comment]
This doesn't happen normally but I think its because ur pc can't handle it try checking task manager and see if anything is causing the game to drop fps, for example, u have another fnf open or u have way too many apps opened if there is nothing causing it to lag and it has a very orange colour next to the app then means ur pc cant handle it, if not and its still doing that then wait for the devs to see how to fix this
